---
abstract: "Search recursively dependencies used in a module's directory"
author:
  - 'smonff <smonff@gmail.com>'
build_requires:
  IO::File: 0
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.74, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Dependencies-Searcher
no_index:
  directory:
    - t
    - inc
requires:
  App::Ack: 0
  Data::Printer: 0
  Module::Version: 0
  Moose: 0
  Test::More: 0
  perl: 5.010
version: 0.05_02
